services:
  xueya:
    image: ghcr.io/czerov/xueya:latest
    container_name: xueya
    network_mode: host
    environment:
      ADDR: ":6644"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
