services:
  xueya:
    build: .
    container_name: xueya
    ports:
      - "6644:6644"
    environment:
      ADDR: ":6644"
      DATA_PATH: "/app/data/records.json"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
