services:
  xueya:
    image: ghcr.io/czerov/xueya:0.1.5
    container_name: xueya
    network_mode: host
    environment:
      ADDR: ":6644"
      LOGIN_USER: admin
      LOGIN_PASS: admin123
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
